version: "2"

services:

  logspout:
    build: logspout
    extends: 
      file: common-services.yml
      service: logspout
    extra_hosts: 
    - "logstash:${LOGSTASH_URL}"
    volumes:
    - ${CA_CERTIFICATE}:/mnt/ca/ca.cert
    - ${CLIENT_CERTIFICATE}:/mnt/cert/client.cert
    - ${CLIENT_KEY}:/mnt/cert/client.key
    command: syslog+tls://${LOGSTASH_URL}:5000

  filebeat:
    build: filebeat
    extends: 
      file: common-services.yml
      service: filebeat
    extra_hosts: 
    - "logstash:${LOGSTASH_URL}"
    volumes:
    - ${CA_CERTIFICATE}:/mnt/ca/ca.cert
    - ${CLIENT_CERTIFICATE}:/mnt/cert/client.cert
    - ${CLIENT_KEY}:/mnt/cert/client.key
    environment:
    - LOGSTASH_SSL_ENABLED=True

volumes:
  fbdata: