version: "2"

services:

  logspout:
    image: ${REGISTRY_URL}/logspout
    extends: 
      file: common-services.yml
      service: logspout
    extra_hosts: 
    - "logstash:${LOGSTASH_URL}"
    volumes:
    - $PWD/ssl/ca.pem:/mnt/ca/ca.cert
    - $PWD/ssl/client-cert.pem:/mnt/cert/client.cert
    - $PWD/ssl/client-key.pem:/mnt/cert/client.key
    command: syslog+tls://${LOGSTASH_URL}:5000
    restart: "unless-stopped"

  filebeat:
    image: ${REGISTRY_URL}/filebeat:${IMAGE_TAG}
    extends: 
      file: common-services.yml
      service: filebeat
    extra_hosts: 
    - "logstash:${LOGSTASH_URL}"
    volumes:
    - $PWD/ssl:/usr/share/filebeat/config/ssl
    environment:
    - LOGSTASH_SSL_ENABLED=True
    restart: "unless-stopped"

volumes:
  fbdata: