version: "2"

services:

  logspout:
    extends: 
      file: common-services.yml
      service: logspout
    extra_hosts: 
    - "logstash:${LOGSTASH_HOST}"
    command: syslog://${LOGSTASH_HOST}:5000

  filebeat:
    image: ${REGISTRY_URL}/filebeat
    extends: 
      file: common-services.yml
      service: filebeat
    volumes: 
    - ${FB_DATA_HOME}:/data
    extra_hosts: 
    - "logstash:${LOGSTASH_HOST}"

volumes:
  fbdata: