version: "2"

services:

  logspout:
    extends: 
      file: common-services.yml
      service: logspout
    command: syslog://127.0.0.1:5000
    network_mode: "container:logstash-srv"

  filebeat:
    build: filebeat
    extends: 
      file: common-services.yml
      service: filebeat
    volumes: 
      - fbdata:/data
    network_mode: "container:logstash-srv"

volumes:
  fbdata: