version: "2"

services:

  logspout:
    build: logspout
    extends: 
      file: common-services.yml
      service: logspout
    extra_hosts: 
    - "logstash:${LOGSTASH_URL}"
    command: syslog+tcp://${LOGSTASH_URL}:5000

  filebeat:
    build: filebeat
    extends: 
      file: common-services.yml
      service: filebeat
    extra_hosts: 
    - "logstash:${LOGSTASH_URL}"

volumes:
  fbdata: