version: "2"

services:

  logspout:
    extends: 
      file: common-services.yml
      service: logspout
    extra_hosts: 
    - "logstash:${LOGSTASH_URL}"
    command: syslog://${LOGSTASH_URL}:5000
    restart: "unless-stopped"

  filebeat:
    image: ${REGISTRY_URL}/filebeat:5.2
    extends: 
      file: common-services.yml
      service: filebeat
    extra_hosts: 
    - "logstash:${LOGSTASH_URL}"
    restart: "unless-stopped"

volumes:
  fbdata: