version: "2"

services:

  logspout:
    extends: 
      file: common-services.yml
      service: logspout
    extra_hosts: 
    - "logstash:${LOGSTASH_HOST}"
    command: syslog://${LOGSTASH_HOST}:5000

  filebeat:
    build: filebeat
    extends: 
      file: common-services.yml
      service: filebeat
    extra_hosts: 
    - "logstash:${LOGSTASH_HOST}"

volumes:
  fbdata: